I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day-3.rpy", line 1095, in script
    show alyssa at nervous with Dissolve(0.3)
  File "game/day-3.rpy", line 1095, in <module>
    show alyssa at nervous with Dissolve(0.3)
NameError: name 'nervous' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day-3.rpy", line 1095, in script
    show alyssa at nervous with Dissolve(0.3)
  File "renpy/ast.py", line 1192, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1151, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 2266, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2259, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/day-3.rpy", line 1095, in <module>
    show alyssa at nervous with Dissolve(0.3)
NameError: name 'nervous' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
Solstice 1.0
Tue Dec 21 14:35:10 2021
