I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day-1.rpy", line 8, in script
    show text "{size=+50}Day 1 - Before{/size}" at glitch(crop=True), trans_text
  File "game/day-1.rpy", line 8, in <module>
    show text "{size=+50}Day 1 - Before{/size}" at glitch(crop=True), trans_text
TypeError: glitch() takes at least 1 argument (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day-1.rpy", line 8, in script
    show text "{size=+50}Day 1 - Before{/size}" at glitch(crop=True), trans_text
  File "renpy/ast.py", line 1192, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1151, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 2266, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2259, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/day-1.rpy", line 8, in <module>
    show text "{size=+50}Day 1 - Before{/size}" at glitch(crop=True), trans_text
TypeError: glitch() takes at least 1 argument (1 given)

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
And So, I Fall 1.0
Wed Dec 29 20:45:44 2021
